//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.19 at 01:08:44 PM IDT 
//


package ac.biu.nlp.nlp.ie.onthefly.input.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ac.biu.nlp.nlp.ace_uima.odie.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ac.biu.nlp.nlp.ace_uima.odie.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OdieInput }
     * 
     */
    public OdieInput createOdieInput() {
        return new OdieInput();
    }

    /**
     * Create an instance of {@link OdieInput.Arguments }
     * 
     */
    public OdieInput.Arguments createOdieInputArguments() {
        return new OdieInput.Arguments();
    }

    /**
     * Create an instance of {@link OdieInput.Corpus }
     * 
     */
    public OdieInput.Corpus createOdieInputCorpus() {
        return new OdieInput.Corpus();
    }

    /**
     * Create an instance of {@link OdieInput.Predicate }
     * 
     */
    public OdieInput.Predicate createOdieInputPredicate() {
        return new OdieInput.Predicate();
    }

    /**
     * Create an instance of {@link OdieInput.UsageSamples }
     * 
     */
    public OdieInput.UsageSamples createOdieInputUsageSamples() {
        return new OdieInput.UsageSamples();
    }

    /**
     * Create an instance of {@link OdieInput.GlobalContext }
     * 
     */
    public OdieInput.GlobalContext createOdieInputGlobalContext() {
        return new OdieInput.GlobalContext();
    }

    /**
     * Create an instance of {@link OdieInput.Arguments.Argument }
     * 
     */
    public OdieInput.Arguments.Argument createOdieInputArgumentsArgument() {
        return new OdieInput.Arguments.Argument();
    }

}
