//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.29 at 01:36:36 PM IST 
//


package ac.biu.nlp.nlp.ace_uima.jaxb;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ApfSourceFileType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ApfSourceFileType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="document">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="entity" type="{}EntityType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="value" type="{}ValueType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="timex2" type="{}Timex2Type" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="relation" type="{}RelationType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="event" type="{}EventType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="URI" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ApfSourceFileType", propOrder = {
    "document"
})
public class ApfSourceFileType {

    @XmlElement(required = true)
    protected ApfSourceFileType.Document document;
    @XmlAttribute(name = "URI", required = true)
    protected String uri;

    /**
     * Gets the value of the document property.
     * 
     * @return
     *     possible object is
     *     {@link ApfSourceFileType.Document }
     *     
     */
    public ApfSourceFileType.Document getDocument() {
        return document;
    }

    /**
     * Sets the value of the document property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApfSourceFileType.Document }
     *     
     */
    public void setDocument(ApfSourceFileType.Document value) {
        this.document = value;
    }

    /**
     * Gets the value of the uri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getURI() {
        return uri;
    }

    /**
     * Sets the value of the uri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setURI(String value) {
        this.uri = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="entity" type="{}EntityType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="value" type="{}ValueType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="timex2" type="{}Timex2Type" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="relation" type="{}RelationType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="event" type="{}EventType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "entity",
        "value",
        "timex2",
        "relation",
        "event"
    })
    public static class Document {

        protected List<EntityType> entity;
        protected List<ValueType> value;
        protected List<Timex2Type> timex2;
        protected List<RelationType> relation;
        protected List<EventType> event;

        /**
         * Gets the value of the entity property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the entity property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEntity().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EntityType }
         * 
         * 
         */
        public List<EntityType> getEntity() {
            if (entity == null) {
                entity = new ArrayList<EntityType>();
            }
            return this.entity;
        }

        /**
         * Gets the value of the value property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the value property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getValue().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ValueType }
         * 
         * 
         */
        public List<ValueType> getValue() {
            if (value == null) {
            	value = new ArrayList<ValueType>();
            }
            return this.value;
        }

        /**
         * Gets the value of the timex2 property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the timex2 property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTimex2().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Timex2Type }
         * 
         * 
         */
        public List<Timex2Type> getTimex2() {
            if (timex2 == null) {
            	timex2 = new ArrayList<Timex2Type>();
            }
            return this.timex2;
        }

        /**
         * Gets the value of the relation property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the relation property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRelation().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RelationType }
         * 
         * 
         */
        public List<RelationType> getRelation() {
            if (relation == null) {
                relation = new ArrayList<RelationType>();
            }
            return this.relation;
        }

        /**
         * Gets the value of the event property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the event property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEvent().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EventType }
         * 
         * 
         */
        public List<EventType> getEvent() {
            if (event == null) {
                event = new ArrayList<EventType>();
            }
            return this.event;
        }

    }

}
