//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.29 at 01:36:36 PM IST 
//


package ac.biu.nlp.nlp.ace_uima.jaxb;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EventType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EventType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="event_argument" type="{}ArgumentType" maxOccurs="2" minOccurs="2"/>
 *         &lt;element name="event_mention" type="{}EventMentionType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="TYPE" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SUBTYPE" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="TENSE" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="MODALITY" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="POLARITY" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="GENERICITY" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EventType", propOrder = {
    "eventArgument",
    "eventMention"
})
public class EventType {

    @XmlElement(name = "event_argument", required = true)
    protected List<ArgumentType> eventArgument;
    @XmlElement(name = "event_mention")
    protected List<EventMentionType> eventMention;
    @XmlAttribute(name = "ID", required = true)
    protected String id;
    @XmlAttribute(name = "TYPE", required = true)
    protected String type;
    @XmlAttribute(name = "SUBTYPE", required = true)
    protected String subtype;
    @XmlAttribute(name = "TENSE", required = true)
    protected String tense;
    @XmlAttribute(name = "MODALITY", required = true)
    protected String modality;
    @XmlAttribute(name = "POLARITY", required = true)
    protected String polarity;
    @XmlAttribute(name = "GENERICITY", required = true)
    protected String genericity;

    /**
     * Gets the value of the eventArgument property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the eventArgument property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEventArgument().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ArgumentType }
     * 
     * 
     */
    public List<ArgumentType> getEventArgument() {
        if (eventArgument == null) {
            eventArgument = new ArrayList<ArgumentType>();
        }
        return this.eventArgument;
    }

    /**
     * Gets the value of the eventMention property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the eventMention property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEventMention().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EventMentionType }
     * 
     * 
     */
    public List<EventMentionType> getEventMention() {
        if (eventMention == null) {
            eventMention = new ArrayList<EventMentionType>();
        }
        return this.eventMention;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTYPE() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTYPE(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the subtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSUBTYPE() {
        return subtype;
    }

    /**
     * Sets the value of the subtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSUBTYPE(String value) {
        this.subtype = value;
    }

    /**
     * Gets the value of the tense property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTENSE() {
        return tense;
    }

    /**
     * Sets the value of the tense property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTENSE(String value) {
        this.tense = value;
    }

    /**
     * Gets the value of the modality property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMODALITY() {
        return modality;
    }

    /**
     * Sets the value of the modality property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMODALITY(String value) {
        this.modality = value;
    }

    /**
     * Gets the value of the polarity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOLARITY() {
        return polarity;
    }

    /**
     * Sets the value of the polarity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOLARITY(String value) {
        this.polarity = value;
    }

    /**
     * Gets the value of the genericity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGENERICITY() {
        return genericity;
    }

    /**
     * Sets the value of the genericity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGENERICITY(String value) {
        this.genericity = value;
    }

}
