//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.29 at 01:36:36 PM IST 
//


package ac.biu.nlp.nlp.ace_uima.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for ExtentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExtentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="charseq">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="START" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                 &lt;attribute name="END" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExtentType", propOrder = {
    "charseq"
})
public class ExtentType {

    @XmlElement(required = true)
    protected ExtentType.Charseq charseq;

    /**
     * Gets the value of the charseq property.
     * 
     * @return
     *     possible object is
     *     {@link ExtentType.Charseq }
     *     
     */
    public ExtentType.Charseq getCharseq() {
        return charseq;
    }

    /**
     * Sets the value of the charseq property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtentType.Charseq }
     *     
     */
    public void setCharseq(ExtentType.Charseq value) {
        this.charseq = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="START" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
     *       &lt;attribute name="END" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Charseq {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "START", required = true)
        protected long start;
        @XmlAttribute(name = "END", required = true)
        protected long end;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the start property.
         * 
         */
        public long getSTART() {
            return start;
        }

        /**
         * Sets the value of the start property.
         * 
         */
        public void setSTART(long value) {
            this.start = value;
        }

        /**
         * Gets the value of the end property.
         * 
         */
        public long getEND() {
            return end;
        }

        /**
         * Sets the value of the end property.
         * 
         */
        public void setEND(long value) {
            this.end = value;
        }

    }

}
