//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.29 at 01:36:36 PM IST 
//


package ac.biu.nlp.nlp.ace_uima.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.excitementproject.eop.common.utilities.datasets.rtepairs.ace.generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SourceFile_QNAME = new QName("", "source_file");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.excitementproject.eop.common.utilities.datasets.rtepairs.ace.generated
     * 
     */
    public ObjectFactory() {/* no init */
    }

    /**
     * Create an instance of {@link EventMentionType }
     * 
     */
    public EventMentionType createEventMentionType() {
        return new EventMentionType();
    }

    /**
     * Create an instance of {@link ApfSourceFileType.Document }
     * 
     */
    public ApfSourceFileType.Document createApfSourceFileTypeDocument() {
        return new ApfSourceFileType.Document();
    }

    /**
     * Create an instance of {@link ApfSourceFileType }
     * 
     */
    public ApfSourceFileType createApfSourceFileType() {
        return new ApfSourceFileType();
    }

    /**
     * Create an instance of {@link EntityMentionType }
     * 
     */
    public EntityMentionType createEntityMentionType() {
        return new EntityMentionType();
    }

    /**
     * Create an instance of {@link EntityType }
     * 
     */
    public EntityType createEntityType() {
        return new EntityType();
    }

    /**
     * Create an instance of {@link ExtentType }
     * 
     */
    public ExtentType createExtentType() {
        return new ExtentType();
    }

    /**
     * Create an instance of {@link RelationMentionType }
     * 
     */
    public RelationMentionType createRelationMentionType() {
        return new RelationMentionType();
    }

    /**
     * Create an instance of {@link ArgumentType }
     * 
     */
    public ArgumentType createArgumentType() {
        return new ArgumentType();
    }

    /**
     * Create an instance of {@link EventType }
     * 
     */
    public EventType createEventType() {
        return new EventType();
    }

    /**
     * Create an instance of {@link RelationType }
     * 
     */
    public RelationType createRelationType() {
        return new RelationType();
    }

    /**
     * Create an instance of {@link ExtentType.Charseq }
     * 
     */
    public ExtentType.Charseq createExtentTypeCharseq() {
        return new ExtentType.Charseq();
    }

    /**
     * Create an instance of {@link ArgumentMentionType }
     * 
     */
    public ArgumentMentionType createArgumentMentionType() {
        return new ArgumentMentionType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ApfSourceFileType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "source_file")
    public JAXBElement<ApfSourceFileType> createSourceFile(ApfSourceFileType value) {
        return new JAXBElement<ApfSourceFileType>(_SourceFile_QNAME, ApfSourceFileType.class, null, value);
    }

}
