//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.07.30 at 12:15:46 PM IDT 
//


package ac.biu.nlp.nlp.ace_uima.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for timex2 element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="timex2">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{}timex2_mention"/>
 *         &lt;/sequence>
 *         &lt;attribute name="ANCHOR_DIR">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *               &lt;enumeration value="WITHIN"/>
 *               &lt;enumeration value="STARTING"/>
 *               &lt;enumeration value="ENDING"/>
 *               &lt;enumeration value="AS_OF"/>
 *               &lt;enumeration value="BEFORE"/>
 *               &lt;enumeration value="AFTER"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/attribute>
 *         &lt;attribute name="ANCHOR_VAL" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="COMMENT" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *         &lt;attribute name="MOD">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *               &lt;enumeration value="BEFORE"/>
 *               &lt;enumeration value="AFTER"/>
 *               &lt;enumeration value="ON_OR_BEFORE"/>
 *               &lt;enumeration value="ON_OR_AFTER"/>
 *               &lt;enumeration value="LESS_THAN"/>
 *               &lt;enumeration value="MORE_THAN"/>
 *               &lt;enumeration value="EQUAL_OR_LESS"/>
 *               &lt;enumeration value="EQUAL_OR_MORE"/>
 *               &lt;enumeration value="START"/>
 *               &lt;enumeration value="MID"/>
 *               &lt;enumeration value="END"/>
 *               &lt;enumeration value="APPROX"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/attribute>
 *         &lt;attribute name="NON_SPECIFIC">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *               &lt;enumeration value="YES"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/attribute>
 *         &lt;attribute name="SET">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *               &lt;enumeration value="YES"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/attribute>
 *         &lt;attribute name="VAL" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "timex2Mention"
})
@XmlRootElement(name = "timex2")
public class Timex2Type {

    @XmlElement(name = "timex2_mention")
    protected Timex2MentionType timex2Mention;
    @XmlAttribute(name = "ANCHOR_DIR")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String anchordir;
    @XmlAttribute(name = "ANCHOR_VAL")
    protected String anchorval;
    @XmlAttribute(name = "COMMENT")
    protected String comment;
    @XmlAttribute(name = "ID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    @XmlAttribute(name = "MOD")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String mod;
    @XmlAttribute(name = "NON_SPECIFIC")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String nonspecific;
    @XmlAttribute(name = "SET")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String set;
    @XmlAttribute(name = "VAL")
    protected String val;

    /**
     * Gets the value of the timex2Mention property.
     * 
     * @return
     *     possible object is
     *     {@link Timex2MentionType }
     *     
     */
    public Timex2MentionType getTimex2Mention() {
        return timex2Mention;
    }

    /**
     * Sets the value of the timex2Mention property.
     * 
     * @param value
     *     allowed object is
     *     {@link Timex2MentionType }
     *     
     */
    public void setTimex2Mention(Timex2MentionType value) {
        this.timex2Mention = value;
    }

    /**
     * Gets the value of the anchordir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getANCHORDIR() {
        return anchordir;
    }

    /**
     * Sets the value of the anchordir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setANCHORDIR(String value) {
        this.anchordir = value;
    }

    /**
     * Gets the value of the anchorval property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getANCHORVAL() {
        return anchorval;
    }

    /**
     * Sets the value of the anchorval property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setANCHORVAL(String value) {
        this.anchorval = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOMMENT() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOMMENT(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the mod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMOD() {
        return mod;
    }

    /**
     * Sets the value of the mod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMOD(String value) {
        this.mod = value;
    }

    /**
     * Gets the value of the nonspecific property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNONSPECIFIC() {
        return nonspecific;
    }

    /**
     * Sets the value of the nonspecific property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNONSPECIFIC(String value) {
        this.nonspecific = value;
    }

    /**
     * Gets the value of the set property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSET() {
        return set;
    }

    /**
     * Sets the value of the set property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSET(String value) {
        this.set = value;
    }

    /**
     * Gets the value of the val property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVAL() {
        return val;
    }

    /**
     * Sets the value of the val property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVAL(String value) {
        this.val = value;
    }

}
