package ac.biu.nlp.nlp.ace_uima.stats;

public enum StatsFieldType {
	ENUM_REL,
	ENUM_SUM,
	COUNT_INT,
	COUNT_DOUBLE,
	COUNT_UNIQUE,
	LIST_COUNTS,
	LIST_VALUES,
	SUM_INT,
	CONST,
	SIGNAL_PERFORMANCE_TRIGGER,
	SIGNAL_PERFORMANCE_ARG_FREE,
	SIGNAL_PERFORMANCE_ARG_DEP,
}
